blog/urls.py
from django.urls import path, include
from .views import home, cine, programacion, tecnologia, videojuegos, tutoriales, contacto, detallePost


app_name = 'blog'

#Importante en el campo name='' poner el nombre exacto al de la categoria 
#que hemos creado en nuestro panel de admin
urlpatterns = [
    path('', home, name='index'),
    path('cine/', cine, name='cine'),
    path('programacion/', programacion, name='programacion'),
    path('tecnologia/', tecnologia, name='tecnologia'),
    path('videojuegos/', videojuegos, name='videojuegos'),
    path('tutoriales/', tutoriales, name='tutoriales'),   
    path('contacto/', tutoriales, name='contacto'), 
    path('post/<int:post_id>/', detallePost, name='post_detalle'),
   

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('blog.urls', namespace='blog')),
    path('cine/', include('blog.urls', namespace='cine')),
    path('programacion/', include('blog.urls', namespace='programacion')),
    path('tecnologia/', include('blog.urls', namespace='tecnologia')),
    path('videojuegos/', include('blog.urls', namespace='videojuegos')),
    path('tutoriales/', include('blog.urls', namespace='tutoriales')),
    path('contacto/', include('blog.urls', namespace='contacto')),
    path('post/<int:pk>/', include('blog.urls', namespace='post_detalle')),
    path('categoria/<int:pk>/', include('blog.urls', namespace='categoria')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.


class Categoria(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField('Nombre de la categoría', max_length = 100, null=False, blank=False)
    estado = models.BooleanField('estado', default=True)
    fecha_creacion = models.DateField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.nombre
    
class Autor(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField( max_length = 100, null=False, blank=False)
    apellidos = models.CharField( max_length = 255, null=False, blank=False)
    instagram = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)
    facebook = models.URLField(null=True, blank=True)
    web = models.URLField(null=True, blank=True)
    email = models.EmailField(blank=True, null=True)
    estado = models.BooleanField(default=True)
    fecha_creacion = models.DateField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = 'Autor'
        verbose_name_plural = 'Autores'

    def __str__(self):
        return "{0},{1}".format(self.apellidos, self.nombre)
    
#Creamos los campos que queremos que tenga nuestro post
#En el caso del tamaño de los campos (max_length) yo he decidido usar estos valores
#pero en contenido no hay límite por ejemplo

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=100, blank=False, null=False)
    slug = models.CharField(max_length=100, blank=False, null=False)
    descripcion = models.CharField(max_length=250, blank=False, null=False)

    #RichTextField es muy interesante para poder personalizar el texto a tu manera y 
    #poder subir imagenes, así como poner links desde nuestro panel de administrador
    contenido = RichTextField()
    imagen = models.ImageField(upload_to="images/")
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    estado = models.BooleanField(default=True)
    fecha_creacion = models.DateField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.titulo

blog/views.py
from django.shortcuts import render
from .models import Post, Categoria
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.core.paginator import Paginator
# Create your views here.


def home(request):
    #realizamos un queryset en donde le pasamos la variable que hemos creado 'buscar'
    #filtramos los post los que esten publicados (estado=True)
    #Usamos paginator, en mi caso en múmero que he usado han sido 3 y 
    # después nos saldría un botón de siguiente para ver los siguientes post
    queryset =  request.GET.get('buscar')
    posts = Post.objects.filter(estado=True)
    paginator = Paginator(posts, 4) 
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    #Realizamos la busqueda por titulo y descripcion
    #__icontains no tiene encuenta mayúsculas y minúsculas, solo con que coincida el texto le vale
    if queryset:
         posts = Post.objects.filter(
              Q(titulo__icontains = queryset) | 
              Q(descripcion__icontains = queryset)
         ).distinct    

    return render(request, 'index.html', {'posts':posts})



def detallePost(request, post_id): 
        post = get_object_or_404(Post,  pk=post_id) 

        return render(request, 'post.html', {'post':post} )


    
#se pasa el mismo nombre que hemos creado en categoría, 
#y así conseguimos todos los posts que su categoría sea Generales
def cine(request):   
       
    queryset = request.GET.get("buscar")
    posts = Post.objects.filter(estado=True, categoria = Categoria.objects.get(nombre__iexact ='Cine')) 
    paginator = Paginator(posts, 3) 
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    if queryset:
        posts = Post.objects.filter(
            Q(titulo__icontains = queryset) | 
            Q(descripcion__icontains = queryset)
        ).distinct

    return render(request, 'generales.html', {'posts':posts})
    

def programacion(request):
    #__iexact omite mayúsculas y minúsculas
    queryset = request.GET.get("buscar")
    posts = Post.objects.filter(estado=True, categoria = Categoria.objects.get(nombre__iexact ='Programacion'))
    paginator = Paginator(posts, 3) 
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    if queryset:
         posts = Post.objects.filter(
              Q(titulo__icontains = queryset) | 
              Q(descripcion__icontains = queryset)
         ).distinct

    return render(request, 'programacion.html', {'posts':posts})
    

def tutoriales(request):
    queryset = request.GET.get("buscar")
    posts = Post.objects.filter(estado=True, categoria = Categoria.objects.get(nombre__iexact ='Tutoriales'))

    paginator = Paginator(posts, 3) 
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    if queryset:
         posts = Post.objects.filter(
              Q(titulo__icontains = queryset) | 
              Q(descripcion__icontains = queryset)
         ).distinct

    return render(request, 'tutoriales.html', {'posts':posts})
    

def tecnologia(request):
    queryset = request.GET.get("buscar")
    posts = Post.objects.filter(estado=True, categoria = Categoria.objects.get(nombre__iexact ='Tecnologia')) 
    paginator = Paginator(posts, 3) 
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    if queryset:
         posts = Post.objects.filter(
              Q(titulo__icontains = queryset) | 
              Q(descripcion__icontains = queryset)
         ).distinct

    return render(request, 'tecnologia.html', {'posts':posts})
    

def videojuegos(request):
    queryset = request.GET.get("buscar")
    posts = Post.objects.filter(estado=True, categoria = Categoria.objects.get(nombre__iexact ='Videojuegos'))
    paginator = Paginator(posts, 3) 
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    if queryset:
         posts = Post.objects.filter(
              Q(titulo__icontains = queryset) | 
              Q(descripcion__icontains = queryset)
         ).distinct

    return render(request, 'videojuegos.html', {'posts':posts})


def contacto(request):
#contacto lo puedes agregar si lo deseas, tienes ya creado el HTML de contacto, yo lo tengo comentado
    return render(request, 'contacto.html')

templates/categoria.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block titulo %} {{ categoria |upper }} | BLOG.DEV {% endblock titulo %}

{% block cuerpo %}
    <div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url({{ categoria.imagen_referencial.url }});">
      <div class="container">
        <div class="row same-height justify-content-center">
          <div class="col-md-12 col-lg-10">
            <div class="post-entry text-center">
              <span class="post-category text-white bg-success mb-3">{{ categoria | upper }}</span>
              <h1 class="mb-4"><a href="{{ request.build_absolute.url }}">{{ categoria | upper }}</a></h1>
            </div>
          </div>
        </div>
      </div>
    </div>

    <section class="site-section py-lg">
      <div class="container">

        <div class="row blog-entries element-animate mb-5">

          <div class="col-md-12 col-lg-12 main-content">
            {% for post in posts %}
              <div class="entry2 mb-5">
                <a href="{% url 'base:detalle_post' post.slug %}"><img src="{{ post.imagen_referencial.url }}" alt="Image" class="img-fluid rounded"></a>
                <span class="post-category text-white bg-primary mb-3">{{ post.categoria }}</span>
                <h2><a href="{% url 'base:detalle_post' post.slug %}">{{ post.titulo }}</a></h2>
                <div class="post-meta align-items-center text-left clearfix">
                  <figure class="author-figure mb-0 mr-3 float-left"><img src="{{ post.autor.imagen_referencial.url }}" alt="Image" class="img-fluid"></figure>
                  <span class="d-inline-block mt-1">POR <a href="#">{{ post.autor }}</a></span>
                  <span>{{ post.fecha_publicacion }}</span>
                </div>
                <p>{{ post.descripcion }}</p>
              </div>
            {% endfor %}
            <div class="row text-center pt-5 border-top">
              <div class="col-md-12">
                <div class="custom-pagination">
                  Página {{ posts.number }} de {{ posts.paginator.num_pages }}
                  {% if posts.has_previous %}
                  <li>
                    <a href="?page={{ posts.previous_page_number }}">{{ posts.previous_page_number }}</a>
                  </li>
                  {% endif %}
                  {% if posts.has_next %}
                  <li>
                    <a href="?page={{ posts.next_page_number }}">{{ posts.next_page_number }}</a>
                  </li>
                  {% endif %}
                </div>
              </div>
            </div>

          </div>

          <!-- END main-content -->

        </div>
      </div>
    </section>
{% endblock cuerpo %}

templates/contacto.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block titulo %} CONTACTO | BLOG.DEV {% endblock titulo %}

{% block cuerpo %}
    <div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('{% static 'images/hero_1.jpg' %}');">
      <div class="container">
        <div class="row same-height justify-content-center">
          <div class="col-md-12 col-lg-10">
            <div class="post-entry text-center">
              <h1 class="mb-4">CONTACTO</h1>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-7 mb-5">
            <form method="post" class="p-5 bg-white">
              {% csrf_token %}
              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="fname">Nombre</label>
                  {{ form.nombre }}
                </div>
                <div class="col-md-6">
                  <label class="text-black" for="lname">Apellidos</label>
                  {{ form.apellidos }}
                </div>
              </div>

              <div class="row form-group">

                <div class="col-md-12">
                  <label class="text-black" for="email">Correo</label>
                  {{ form.correo }}
                </div>
              </div>

              <div class="row form-group">

                <div class="col-md-12">
                  <label class="text-black" for="subject">Asunto</label>
                  {{ form.asunto }}
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <label class="text-black" for="message">Mensaje</label>
                  {{ form.mensaje }}
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <button type="submit" class="btn btn-primary py-2 px-4 text-white">ENVIAR </button>
                </div>
              </div>


            </form>
          </div>
          <div class="col-md-5">

            <div class="p-4 mb-3 bg-white">
              <p class="mb-0 font-weight-bold">Direccion</p>
              <p class="mb-4">{{ web.direccion }}</p>

              <p class="mb-0 font-weight-bold">Teléfono</p>
              <p class="mb-4"><a href="#">{{ web.telefono }}</a></p>

              <p class="mb-0 font-weight-bold">Correo</p>
              <p class="mb-0"><a href="#">{{ web.email }}</a></p>

            </div>

            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">Nosotros</h3>
              <p>{{ web.nosotros }}</p>
              <p><a href="#" class="btn btn-primary px-4 py-2 text-white">Learn More</a></p>
            </div>

          </div>
        </div>
      </div>
    </div>
{% endblock cuerpo %}

templates/generales.html
{% extends 'index.html' %}
{% load static %}
{% block titulo %}
Cine
{% endblock titulo %}

{% block content %}


  
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
 <head>
   <title>{% block titulo %}Blog{% endblock titulo %}</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700|Playfair+Display:400,700,900" rel="stylesheet">
   <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
   <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
   <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
   <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
   <link rel="stylesheet" href="{% static 'css/aos.css' %}">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block extracss %}
  {% endblock extracss %}
 </head>
 <body>

 <div class="site-wrap">
   <div class="site-mobile-menu">
     <div class="site-mobile-menu-header">
       <div class="site-mobile-menu-close mt-3">
         <span class="icon-close2 js-menu-toggle"></span>
       </div>
     </div>
     <div class="site-mobile-menu-body"></div>
   </div>
   <header class="site-navbar pt-3" role="banner">
     <div class="container-fluid">
       <div class="row align-items-center">
         <div class="col-6 col-xl-6 logo">
           <h1 class="mb-0"><a href="{% url 'blog:index'  %}" class="text-black h2 mb-0">BLOG</a></h1>
         </div>
         <!--No te olvides de poner tus redes sociales-->
         <div class="col-6 mr-auto py-3 text-right" style="position: relative; top: 3px;">
           <div class="social-icons d-inline">
            <a href="{{ sociales.linkedin }}" target="_blank"><span class="icon-linkedin"></span></a>
               <a href="{{ sociales.facebook }}" target="_blank"><span class="icon-facebook"></span></a>
               <a href="{{ sociales.twitter }}" target="_blank"><span class="icon-twitter"></span></a>
               <a href="{{ sociales.instagram }}" target="_blank"><span class="icon-instagram"></span></a>
           </div>
           <a href="#" class="site-menu-toggle js-menu-toggle text-black d-inline-block d-xl-none"><span class="icon-menu h3"></span></a></div>
         </div>
         <!--Hacemos un if para cuando estemos navegando por nuestra web según donde estemos
          te indique en que sección estás con el metodo active-->
         <div class="col-12 d-none d-xl-block border-top">
           <nav class="site-navigation text-center " role="navigation">
             <ul class="site-menu js-clone-nav mx-auto d-none d-lg-block mb-0">
               <li class="{% if request.path == '/' %}active{% endif %}"><a href="{% url 'blog:index'  %}">Inicio</a></li>
               <li class="{% if request.path == '/cine/' %}active{% endif %}"><a href="{% url 'blog:cine' %}">Cine</a></li>
               <li class="{% if request.path == '/videojuegos/' %}active{% endif %}"><a href="{% url 'blog:videojuegos' %}">Videojuegos</a></li>
               <li class="{% if request.path == '/tecnologia/' %}active{% endif %}"><a href="{% url 'blog:tecnologia' %}">Tecnología</a></li>
               <li class="{% if request.path == '/programacion/' %}active{% endif %}"><a href="{% url 'blog:programacion' %}">Programación</a></li>
               <li class="{% if request.path == '/tutoriales/' %}active{% endif %}"><a href="{% url 'blog:tutoriales' %}">Tutoriales</a></li>
              <!-- <li><a href="{% url 'blog:contacto' %}">Contacto</a></li>-->
             </ul>
           </nav>
         </div>
       </div>
   </header>
   <!--Una barra de busqueda simple-->
{% block barra_busqueda %}
   <div class="container">
      <div class="row">
        <div class="col-md-12 search">
          <form method="get">
            <div id="custom-search-input">
              <div class="input-group col-md-10">
                <input type="text" class="form-control" placeholder="Buscar" id="buscar" value="{{request.GET.get.buscar}}">
                <span class="input-group-list">
                  <i class="icon icon-search"></i>
                    <button type="submit" class="boton btn-success" style="background-color: #2f89fc; border-color: #2f89fc;color: whitesmoke;">Buscar</button>                 
                </span>
              </div> 
            </div>
          </form>
        </div>
      </div>
   </div>
{% endblock barra_busqueda %}
{% csrf_token %}
<!--Creamos un if, si existen post pues los recoremos con un bucle for-->
{% block cuerpo %}
   <div class="slide-one-item home-slider owl-carousel">
       <div class="container">
         <div class="row same-height align-items-center">
          {% if posts %}
            {% for post in posts %}
           <div class="col-md-12 col-lg-6">
           <div class="card" style="text-align: center;max-height: 600px;background-color: #191919;margin-top: 5%;">
             <div class="post-entry">
               <span class="post-category text-white bg-success mb-3">{{ post.categoria | upper }}</span>
               <div class="post-meta align-items-center text-left">
                 <img src="{{ post.imagen.url}}" alt="Image" class="img-fluid" style="width: 100%; max-height: 320px;">
                 <h2 class="mb-4" style="text-align: center;"><a href="{% url 'blog:post_detalle' post.id %}" style="color: aliceblue;">{{ post.titulo|truncatechars:35 }}</a></h2>
                 <div class="col-md-8" style="margin-top: 5%; margin-bottom: 4%;">
                  <p >{{post.descripcion|truncatechars:100}}</p>
                  <a href="{% url 'blog:post_detalle' post.id %}" style="text-decoration: none;color: rgb(148, 147, 147);">Leer más...</a>
                  <!--<p>{{ post.autor }}</p>-->
                  <p>{{ post.fecha_creacion }}</p>               
                 </div>                             
               </div>
             </div>
           </div>
           </div>
           {% endfor %}
           {% else %}
           <h2>No hay posts</h2>
           {% endif %}
         </div>
       </div>
     </div>
   </div>
   <!--Utilizamos paginator y creamos unos Anchor para ver los siguientes post o ver los anteriores
    utilizando un if para que nos muestre el anchor creado si hay más post o no-->
   <div class="row">
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
      <div class="col-6-md-6 col-sm-6 col-lg6 col-xs-6 float-right">
        {% if posts.has_previous %}
        <div class="clearfix">
          <a href="?page={{posts.previous_page_number}}{% if request.GET.search %} &q={{ request.GET.search }}{% endif %}" class="btn btn-primary float-left">Anterior</a>
        </div>
        {% elif posts.has_next%}
        <div class="clearfix">
          <a href="?page={{posts.next_page_number}}{% if request.GET.search %} &q={{ request.GET.search }}{% endif %}" class="btn btn-primary float-left">Siguiente</a>
        </div>
        {% endif %}
      </div>
    </div>
   </div>
   
  

 {% endblock cuerpo %}

       <div class="row">
         <div class="col-12 text-center">
           <p>            
             Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved            
             </p>
         </div>
       </div>
     </div>
   </div>
 </div>
 <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
 <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
 <script src="{% static 'js/jquery-ui.js' %}"></script>
 <script src="{% static 'js/popper.min.js' %}"></script>
 <script src="{% static 'js/bootstrap.min.js' %}"></script>
 <script src="{% static 'js/owl.carousel.min.js' %}"></script>
 <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
 <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
 <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
 <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
 <script src="{% static 'js/aos.js' %}"></script>
 <script src="{% static 'js/main.js' %}"></script>
{% block extrajs %}
{% endblock extrajs %}
 </body>
</html>

templates/post.html
{% extends 'index.html' %}
{% load static %}
{% block titulo %} {{ post.titulo |upper }} | BLOG{% endblock titulo %}

{% block cuerpo %}
    <div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('{{ post.imagen.url}}')">
      <div class="container">
        <div class="row same-height justify-content-center">
          <div class="col-md-12 col-lg-10">
            <div class="post-entry text-center">
              <span class="post-category text-white bg-success mb-3">{{ post.categoria}}</span>
              <h1 class="mb-4">{{ post.titulo |upper }}</h1>
              
            </div>
          </div>
        </div>
      </div>
    </div>

    <section class="site-section py-lg">
      <div class="container">
        <div class="row blog-entries element-animate">

          <div class="col-md-12 col-lg-8 main-content">

            <div class="post-content-body">
              {{ post.contenido |safe }}
            </div>
            <h4>{{ post.autor }}</h4>            
            <span>{{ post.fecha_creacion }}</span>
          </div>
          <div class="post-meta align-items-center text-center">
          </div>     
    </section>      
      
      <script>      
      (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://blog-dev2.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
      })();
      </script>
      <noscript> <a href="https://disqus.com/?ref_noscript"></a></noscript>
    </div>
    </section>
{% endblock cuerpo %}

templates/programacion.html
{% extends 'index.html' %}
{% load static %}
{% block titulo %}
Programación
{% endblock titulo %}

{% block imagen %} 
    {% static 'img/generales.jpg' %}

{% endblock imagen %}

{% block titulo_principal %}

    Post Programación 

{% endblock titulo_principal %}

templates/tecnologia.html
{% extends 'index.html' %}
{% load static %}
{% block titulo %}
Tecnología
{% endblock titulo %}

{% block imagen %} 
    {% static 'img/generales.jpg' %}

{% endblock imagen %}

{% block titulo_principal %}

    Post Tecnología 

{% endblock titulo_principal %}

templates/tutoriales.html
{% extends 'index.html' %}
{% load static %}
{% block titulo %}
Tutoriales
{% endblock titulo %}

{% block imagen %} 
    {% static 'img/generales.jpg' %}

{% endblock imagen %}

{% block titulo_principal %}

    Post Tutoriales 

{% endblock titulo_principal %}

templates/videojuegos.html
{% extends 'index.html' %}
{% load static %}
{% block titulo %}
Videojuegos
{% endblock titulo %}

{% block imagen %} 
    {% static 'img/generales.jpg' %}

{% endblock imagen %}

{% block titulo_principal %}

    Post Videojuegos 

{% endblock titulo_principal %}